### ISSUE TITLE
Not working and can you add Tickets?

### ISSUE THREAD

**Issue by izaan22** [Brionjv/Miitopia-Save-Editor-Switch-Version#1]
Save editor can't even run and when i download on chrome it say "This file is not commonly downloaded and may be dangerous."

And also can you add Tickets and Outing Tickets?

**Comment by Brionjv** [comment]
click on keep to download, I work on a better version, tickets will be added too

**Comment by izaan22** [comment]
The update one fixed save editor can't even run
