### ISSUE TITLE
Unlock Amiibo outfits and Inn Options don't work.

### ISSUE THREAD

**Issue by Rocker26a** [Brionjv/Miitopia-Save-Editor-Switch-Version#10]
Trying to save either results in this error.
![image](https://user-images.githubusercontent.com/23735586/121758911-4d843e80-cb1b-11eb-8907-fe83f5470534.png)

**Comment by Brionjv** [comment]
This error is fixed in last version, thanks

**Comment by Rocker26a** [comment]
I'm on the latest version, and no it wasn't.
