### ISSUE TITLE
Requests for future versions: Change "Hero" Mii/transfer Miis between saves?

### ISSUE THREAD

**Issue by Rocker26a** [Brionjv/Miitopia-Save-Editor-Switch-Version#11]
Something I've wanted since I first got the game was the ability to change the playable Mii. It doesn't let you use a pre-made Mii, you have to either make one fresh or use one from the console's data, which doesn't save the make-up.

I don't know if it'd be as simple as, like. Checking a box that's labelled "Hero", or if you could like. Have an export/import function for specific Miis. I'd guess not, but I'd be very appreciative of something to achieve that kind of result!

**Comment by Brionjv** [comment]
I'll try this, if it's possible

**Comment by egx-lab** [comment]
If possible, would you also allow for the rest of the party members to be changed as well. I'm happy with my Hero but I wish there was a way to change some of my party members for other miis I've already made on my save file.

**Comment by Brionjv** [comment]
I'll try to do this too
