### ISSUE TITLE
Multiple EXEs in every release.

### ISSUE THREAD

**Issue by Rocker26a** [Brionjv/Miitopia-Save-Editor-Switch-Version#12]
The save editor has a somewhat confusing directory, with multiple EXEs for the save editor itself. The latest one having four including the debug versions. Two in "Miitopia Save Editor Switch Version\obj\", and another two in "Miitopia Save Editor Switch Version\bin".

**Comment by Brionjv** [comment]
use "Miitopia Save Editor Switch Version/bin/Debug/" or download archive in release page
