### ISSUE TITLE
Add Mii editor for access key offline?

### ISSUE THREAD

**Issue by izaan22** [Brionjv/Miitopia-Save-Editor-Switch-Version#3]
Add Mii editor if ban/hacked switch mii access key offline to download

**Comment by sneedfeedseed** [comment]
hmm im not sure if it can work that way, I brought up an idea in the other github to give the option to import/export miis to each other, so that people that have online can download them and give them to people that dont!

**Comment by Brionjv** [comment]
See version 1.6.0
