### ISSUE TITLE
Unlockables

### ISSUE THREAD

**Issue by ShrektheAlmightyOgrelord** [Brionjv/Miitopia-Save-Editor-Switch-Version#6]
It won't let me unlock all the weapons, is there a way to fix this? Everything else works great except for this.

**Comment by pitrako** [comment]
Yeah, It unlocks amiibo outfits but no weapons or armors.

**Comment by ShrektheAlmightyOgrelord** [comment]
Ok, I just saw the circle with every class around it and assumed that it would unlock outfits, but now I know it just allows you to have all jobs from the start
